### ISSUE TITLE
Training file format

### ISSUE THREAD

**Issue by Soe2Lwin** [USC-NLP-17/NaiveBayesHindiSummary#2]
I want to test Myanmar text summarization using Naive Bayes.
May I know corpus file format.
Please help me.
Thank you

**Comment by amjha** [comment]
You can find more details here: https://github.com/USC-NLP-17/NBNewSummarizer

**Comment by Soe2Lwin** [comment]
Thank you so much .I will try it.

________________________________

**Comment by Soe2Lwin** [comment]
Thank you so much.I will try it.
